export const POPUP_COMMANDS = {
    START_EXPORT: 'START_FULL_AUTOMATION',
    OPEN_LESSON_RESET: 'OPEN_LESSON_RESET',
    OPEN_ACTION_RECORDER: 'OPEN_ACTION_RECORDER',
    OPEN_BATCH_LESSON_ACCESS: 'OPEN_BATCH_LESSON_ACCESS',
    OPEN_BATCH_USER_ONBOARDING: 'OPEN_BATCH_USER_ONBOARDING',
    OPEN_BATCH_USER_MANAGEMENT: 'OPEN_BATCH_USER_MANAGEMENT',
    OPEN_BATCH_SECTION_CREATION: 'OPEN_BATCH_SECTION_CREATION',
    OPEN_BATCH_SECTION_DELETION: 'OPEN_BATCH_SECTION_DELETION',
    OPEN_VIDEO_ATTACHMENT: 'OPEN_VIDEO_ATTACHMENT',
    OPEN_EXECUTION_HISTORY: 'OPEN_EXECUTION_HISTORY'
} as const;

export const WINDOW_MESSAGE_TYPES = {
    START_EXPORT: 'EDVIBE_TOOLBOX_START_ALL',
    OPEN_LESSON_RESET: 'EDVIBE_TOOLBOX_OPEN_RESET',
    OPEN_ACTION_RECORDER: 'EDVIBE_TOOLBOX_OPEN_RECORDER',
    OPEN_BATCH_LESSON_ACCESS: 'EDVIBE_TOOLBOX_OPEN_BATCH_LESSON_ACCESS',
    OPEN_BATCH_USER_ONBOARDING: 'EDVIBE_TOOLBOX_OPEN_BATCH_USER_ONBOARDING',
    OPEN_BATCH_USER_MANAGEMENT: 'EDVIBE_TOOLBOX_OPEN_BATCH_USER_MANAGEMENT',
    OPEN_BATCH_SECTION_CREATION: 'EDVIBE_TOOLBOX_OPEN_BATCH_SECTION_CREATION',
    OPEN_BATCH_SECTION_DELETION: 'EDVIBE_TOOLBOX_OPEN_BATCH_SECTION_DELETION',
    OPEN_VIDEO_ATTACHMENT: 'EDVIBE_TOOLBOX_OPEN_VIDEO_ATTACHMENT',
    OPEN_EXECUTION_HISTORY: 'EDVIBE_TOOLBOX_OPEN_EXECUTION_HISTORY',
    EXPORT_STATUS: 'EDVIBE_TOOLBOX_EXPORT_STATUS',
    STORAGE_REQUEST: 'EDVIBE_TOOLBOX_STORAGE_REQUEST',
    STORAGE_RESPONSE: 'EDVIBE_TOOLBOX_STORAGE_RESPONSE'
} as const;

export const RUNTIME_MESSAGE_ACTIONS = {
    EXPORT_STATUS: 'EXPORT_STATUS'
} as const;

export const EXPORT_STATES = {
    STARTED: 'started',
    COMPLETE: 'complete',
    ERROR: 'error'
} as const;

export const STORAGE_ACTIONS = {
    GET: 'get',
    SET: 'set'
} as const;

export const STORAGE_KEYS = {
    EXECUTION_HISTORY_PREFERENCES: 'executionHistoryPreferences'
} as const;

export const COMMAND_ROUTES = {
    [POPUP_COMMANDS.START_EXPORT]: {
        type: WINDOW_MESSAGE_TYPES.START_EXPORT,
        info: 'Automation sequence channeled to page engine.'
    },
    [POPUP_COMMANDS.OPEN_LESSON_RESET]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_LESSON_RESET,
        info: 'Lesson reset workflow opened.'
    },
    [POPUP_COMMANDS.OPEN_ACTION_RECORDER]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_ACTION_RECORDER,
        info: 'Action recorder opened.'
    },
    [POPUP_COMMANDS.OPEN_BATCH_LESSON_ACCESS]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_BATCH_LESSON_ACCESS,
        info: 'Batch lesson access opened.'
    },
    [POPUP_COMMANDS.OPEN_BATCH_USER_ONBOARDING]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_BATCH_USER_ONBOARDING,
        info: 'Batch user onboarding opened.'
    },
    [POPUP_COMMANDS.OPEN_BATCH_USER_MANAGEMENT]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_BATCH_USER_MANAGEMENT,
        info: 'Batch user management opened.'
    },
    [POPUP_COMMANDS.OPEN_BATCH_SECTION_CREATION]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_BATCH_SECTION_CREATION,
        info: 'Batch section creation opened.'
    },
    [POPUP_COMMANDS.OPEN_BATCH_SECTION_DELETION]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_BATCH_SECTION_DELETION,
        info: 'Batch section deletion opened.'
    },
    [POPUP_COMMANDS.OPEN_VIDEO_ATTACHMENT]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_VIDEO_ATTACHMENT,
        info: 'YouTube video attachment opened.'
    },
    [POPUP_COMMANDS.OPEN_EXECUTION_HISTORY]: {
        type: WINDOW_MESSAGE_TYPES.OPEN_EXECUTION_HISTORY,
        info: 'Execution history opened.'
    }
} as const;

export type PopupCommand = typeof POPUP_COMMANDS[keyof typeof POPUP_COMMANDS];
export type MainCommandType = typeof COMMAND_ROUTES[keyof typeof COMMAND_ROUTES]['type'];
export type ExportState = typeof EXPORT_STATES[keyof typeof EXPORT_STATES];
export type StorageAction = typeof STORAGE_ACTIONS[keyof typeof STORAGE_ACTIONS];
export type StorageKey = typeof STORAGE_KEYS[keyof typeof STORAGE_KEYS];
export type CommandRoute = typeof COMMAND_ROUTES[PopupCommand];

export const MAIN_COMMAND_TYPES: ReadonlySet<string> = new Set(Object.values(COMMAND_ROUTES).map(({ type }) => type));
export const EXPORT_STATE_VALUES: ReadonlySet<string> = new Set(Object.values(EXPORT_STATES));
export const STORAGE_ACTION_VALUES: ReadonlySet<string> = new Set(Object.values(STORAGE_ACTIONS));
export const STORAGE_KEY_VALUES: ReadonlySet<string> = new Set(Object.values(STORAGE_KEYS));
